# Generated by Django 5.0.7 on 2024-08-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
         migrations.AddField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=100, default=''),
        ),
    ]
